series_db = {}

def add_series(nombre, relacionadas):
    if nombre not in series_db:
        series_db[nombre] = []
    series_db[nombre] = list(set(series_db[nombre] + relacionadas))


add_series("Serie", ['Series Relacionadas'])
add_series("Game of Thrones", ['The Witcher;Vikings;The Mandalorian;The Lord of the Rings: The Rings of Power;Westworld;Breaking Bad;Stranger Things;The Expanse;Spartacus;House of the Dragon'])
add_series("Stranger Things", ['The Umbrella Academy;Dark;Locke & Key;Riverdale;Chilling Adventures of Sabrina;Supernatural;Outer Banks;The OA;The Society;Black Mirror'])
add_series("Breaking Bad", ['Better Call Saul;The Sopranos;Ozark;Fargo;Narcos;The Wire;Dexter;Mad Men;Sons of Anarchy;The Shield'])
add_series("The Mandalorian", ['Star Wars: The Clone Wars;Star Wars Rebels;Obi-Wan Kenobi;Game of Thrones;Loki;The Witcher;Stranger Things;Lost in Space;The Expanse;Westworld'])
add_series("The Witcher", ['Game of Thrones;Shadow and Bone;Vikings;His Dark Materials;Carnival Row;The Mandalorian;Lucifer;Castlevania;Dark;Penny Dreadful'])
add_series("Loki", ['Wandavision;Hawkeye;The Falcon and the Winter Soldier;The Mandalorian;Moon Knight;Guardians of the Galaxy;Doctor Who;Rick and Morty;What If…?;She-Hulk'])
add_series("The Expanse", ['Battlestar Galactica;Star Trek: Discovery;Star Trek: Picard;Dark Matter;Altered Carbon;Stranger Things;Westworld;Lost in Space;The Mandalorian;Foundation'])
add_series("Westworld", ['Altered Carbon;Black Mirror;Game of Thrones;The Expanse;Stranger Things;Person of Interest;The 100;Lost;Humans;Dark'])
add_series("Vikings", ['The Last Kingdom;Game of Thrones;Spartacus;The Witcher;Marco Polo;Rome;Penny Dreadful;Black Sails;The Mandalorian;Knightfall'])
add_series("The Umbrella Academy", ['Stranger Things;Locke & Key;Chilling Adventures of Sabrina;The Society;Dark;Outer Banks;Shadow and Bone;Titans;Misfits;Deadly Class'])
add_series("Friends", ['How I Met Your Mother;The Office;Big Bang Theory;Modern Family;Seinfeld;Brooklyn Nine-Nine;New Girl;Scrubs;Community;Parks and Recreation'])
add_series("The Office", ['Friends;Parks and Recreation;Brooklyn Nine-Nine;Scrubs;Community;30 Rock;Modern Family;How I Met Your Mother;Seinfeld;Arrested Development'])
add_series("Parks and Recreation", ['The Office;Brooklyn Nine-Nine;30 Rock;Friends;Community;Scrubs;Modern Family;How I Met Your Mother;Seinfeld;Arrested Development'])
add_series("Brooklyn Nine-Nine", ['The Office;Parks and Recreation;Scrubs;Community;Friends;Modern Family;30 Rock;How I Met Your Mother;Seinfeld;Arrested Development'])
add_series("Modern Family", ['Friends;How I Met Your Mother;The Office;Parks and Recreation;Scrubs;Brooklyn Nine-Nine;Community;30 Rock;Seinfeld;Arrested Development'])
add_series("Seinfeld", ['Friends;The Office;How I Met Your Mother;Parks and Recreation;Modern Family;Brooklyn Nine-Nine;Scrubs;Community;30 Rock;Arrested Development'])
add_series("How I Met Your Mother", ['Friends;The Office;Modern Family;Parks and Recreation;Scrubs;Brooklyn Nine-Nine;Community;30 Rock;Seinfeld;Arrested Development'])
add_series("Community", ['The Office;Friends;Parks and Recreation;Scrubs;Brooklyn Nine-Nine;30 Rock;Modern Family;How I Met Your Mother;Seinfeld;Arrested Development'])
add_series("Scrubs", ['The Office;Friends;Community;Parks and Recreation;Brooklyn Nine-Nine;Modern Family;30 Rock;How I Met Your Mother;Seinfeld;Arrested Development'])
add_series("30 Rock", ['The Office;Parks and Recreation;Friends;Community;Scrubs;Brooklyn Nine-Nine;Modern Family;How I Met Your Mother;Seinfeld;Arrested Development'])
add_series("Arrested Development", ['Friends;The Office;Parks and Recreation;Brooklyn Nine-Nine;Community;Scrubs;30 Rock;Modern Family;How I Met Your Mother;Seinfeld'])
add_series("Dexter", ['Breaking Bad;Better Call Saul;Ozark;Fargo;Narcos;The Wire;Mad Men;Sons of Anarchy;The Shield;True Detective'])
add_series("True Detective", ['Breaking Bad;Dexter;Better Call Saul;Ozark;Fargo;Narcos;The Wire;Mad Men;Sons of Anarchy;The Shield'])
add_series("Ozark", ['Breaking Bad;Better Call Saul;Dexter;Fargo;Narcos;The Wire;Mad Men;Sons of Anarchy;The Shield;True Detective'])
add_series("Better Call Saul", ['Breaking Bad;Ozark;Dexter;Fargo;Narcos;The Wire;Mad Men;Sons of Anarchy;The Shield;True Detective'])
add_series("Narcos", ['Breaking Bad;Dexter;Ozark;Better Call Saul;Fargo;The Wire;Mad Men;Sons of Anarchy;The Shield;True Detective'])
add_series("The Wire", ['Breaking Bad;Dexter;Ozark;Better Call Saul;Fargo;Narcos;Mad Men;Sons of Anarchy;The Shield;True Detective'])
add_series("Mad Men", ['Breaking Bad;Dexter;Ozark;Better Call Saul;Fargo;Narcos;The Wire;Sons of Anarchy;The Shield;True Detective'])
add_series("Sons of Anarchy", ['Breaking Bad;Dexter;Ozark;Better Call Saul;Fargo;Narcos;The Wire;Mad Men;The Shield;True Detective'])
add_series("The Shield", ['Breaking Bad;Dexter;Ozark;Better Call Saul;Fargo;Narcos;The Wire;Mad Men;Sons of Anarchy;True Detective'])
add_series("House of Cards", ['Breaking Bad;Better Call Saul;Ozark;Fargo;Narcos;The Wire;Mad Men;Sons of Anarchy;The Shield;True Detective'])
add_series("Narcos: Mexico", ['Narcos;Breaking Bad;Better Call Saul;Ozark;Fargo;The Wire;Mad Men;Sons of Anarchy;The Shield;True Detective'])
add_series("Mindhunter", ['True Detective;Breaking Bad;Dexter;Ozark;Better Call Saul;Fargo;Narcos;The Wire;Mad Men;Sons of Anarchy'])
add_series("Black Mirror", ['Westworld;Altered Carbon;Stranger Things;Person of Interest;The 100;Lost;Humans;Dark;The Expanse;The Mandalorian'])
add_series("Altered Carbon", ['Westworld;Black Mirror;Stranger Things;The Expanse;Lost in Space;Game of Thrones;Dark;Humans;Person of Interest;The 100'])
add_series("The 100", ['Lost;Person of Interest;Stranger Things;Westworld;Black Mirror;Altered Carbon;Humans;The Expanse;Game of Thrones;Dark'])
add_series("Lost", ['The 100;Person of Interest;Stranger Things;Westworld;Black Mirror;Altered Carbon;Humans;The Expanse;Game of Thrones;Dark'])
add_series("Person of Interest", ['Westworld;Altered Carbon;Black Mirror;The 100;Lost;Humans;Stranger Things;The Expanse;Game of Thrones;Dark'])
add_series("Humans", ['Westworld;Altered Carbon;Black Mirror;The 100;Lost;Person of Interest;Stranger Things;The Expanse;Game of Thrones;Dark'])
add_series("Shadow and Bone", ['The Witcher;Game of Thrones;Vikings;Carnival Row;Lucifer;Castlevania;Dark;Penny Dreadful;The Mandalorian;Loki'])
add_series("Penny Dreadful", ['The Witcher;Game of Thrones;Vikings;Shadow and Bone;Carnival Row;Lucifer;Castlevania;Dark;The Mandalorian;Loki'])
add_series("Lucifer", ['The Witcher;Game of Thrones;Vikings;Shadow and Bone;Carnival Row;Penny Dreadful;Castlevania;Dark;The Mandalorian;Loki'])
add_series("Castlevania", ['The Witcher;Game of Thrones;Vikings;Shadow and Bone;Carnival Row;Lucifer;Penny Dreadful;Dark;The Mandalorian;Loki'])
add_series("Carnival Row", ['The Witcher;Game of Thrones;Vikings;Shadow and Bone;Lucifer;Penny Dreadful;Castlevania;Dark;The Mandalorian;Loki'])
